# Generated by Django 5.2.2 on 2025-07-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='service',
            field=models.ManyToManyField(default=None, related_name='masters', to='core.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(default=None, related_name='orders', to='core.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='masters', verbose_name='Фото'),
        ),
    ]
