# Generated by Django 5.2.2 on 2025-07-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_master_service_order_service_alter_master_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='service',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(default=None, related_name='masters', to='core.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(default=None, related_name='orders', to='core.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Время выполнения в минутах', verbose_name='Длительность'),
        ),
    ]
