# Generated by Django 5.2.2 on 2025-08-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_master_options_alter_order_options_and_more'),
        ('core', '0009_order_view_count_alter_review_rating'),
    ]

    operations = [
    ]
